In [40]:
import pandas as pd
import numpy as np

In [4]:
posts = pd.read_csv("./data/iron_march_201911/csv/core_message_posts.csv")

In [5]:
posts

msg_id  msg_topic_id    msg_date  \
0           1             1  1316144998   
1           2             2  1316174048   
2           3             2  1316183999   
3           4             2  1316186941   
4           5             2  1316187178   
...       ...           ...         ...   
21710   26558          5795  1511213441   
21711   26559          5975  1511220489   
21712   26560          5743  1511222895   
21713   26561          5973  1511236152   
21714   26562          5976  1511236838   

                                                msg_post  \
0      <p>The best first post to make on our forums i...   
1      \n<p>Who are we hosting this forum from?</p>\n...   
2      <p>Crisis Host - they basically provide hostin...   
3      <p>Thank you, I'll make a note of it, I am ver...   
4      <p>If you mean the dark+orange skin then that'...   
...                                                  ...   
21710  \n<p>\n\tOf course I know the Akbaria, it's a ...   
21711  \n<p>\n\t<a href="https://scottishnationalists...   
21712  \n<p>\n\tВидя ли се в The Independent? :D\n</p...   
21713  <p>\n\t/Orthodox/ general and a couple of shit...   
21714  <p>\n\tcan i get in that chess club discord th...   

                           msg_post_key  msg_author_id   msg_ip_address  \
0      3320f7f06c422ef0fb77342724b4fd24              1  178.140.119.217   
1      9204e4883321af2275a37138d054a3f1             11    109.78.212.13   
2      12fd0309239711d02b39127de3502c51              1  178.140.119.217   
3      0658c6f99ac18d90609ea074ae5eefe6             11    109.78.212.13   
4      570257864e3cb812eebc2de5e5919080              1  178.140.119.217   
...                                 ...            ...              ...   
21710                                 0          13298   141.101.104.54   
21711                                 0           9792  141.101.107.205   
21712                                 0          14702    162.158.34.41   
21713                                 0          14072   172.68.189.140   
21714                                 0          13861    162.158.62.46   

       msg_is_first_post  
0                      1  
1                      1  
2                      0  
3                      0  
4                      0  
...                  ...  
21710                  0  
21711                  1  
21712                  0  
21713                  0  
21714                  1  

[21715 rows x 8 columns]

In [6]:
topics = pd.read_csv("./data/iron_march_201911/csv/core_message_topics.csv")

In [7]:
topics

mt_id     mt_date                     mt_title  mt_hasattach  \
0         1  1316144998  Introductions are important             0   
1         2  1316174048                    Our hosts             0   
2         3  1316223829                Re: Nova Roma             0   
3         5  1316528414  Introductions are important             0   
4         6  1316700737                          msn             0   
...     ...         ...                          ...           ...   
4470   5972  1511108042           whats the link yh?             0   
4471   5973  1511158382                        sssss             0   
4472   5974  1511203603                          das             0   
4473   5975  1511220489                          SNS             0   
4474   5976  1511236838                      discord             0   

      mt_starter_id  mt_start_time  mt_last_post_time  mt_to_count  \
0                 1     1316144998         1316144998            1   
1                11     1316174047         1316187891            1   
2                16     1316223829         1316224790            1   
3                 1     1316528414         1316529737            1   
4                 1     1316700737         1316701077            1   
...             ...            ...                ...          ...   
4470          14041     1511108042         1511108079            2   
4471          14550     1511158382         1511236152            2   
4472           9288     1511203603         1511203603            2   
4473           9792     1511220489         1511220489            2   
4474          13861     1511236838         1511236838            2   

      mt_to_member_id  mt_replies  mt_first_msg_id  mt_is_draft  \
0                  23           0                1            0   
1                   1           4                2            0   
2                  14           1                7            0   
3                  20           1               12            0   
4                  11           1               14            0   
...               ...         ...              ...          ...   
4470                0           2            26550            0   
4471                0           2            26554            0   
4472                0           1            26556            0   
4473                0           1            26559            0   
4474                0           1            26562            0   

      mt_is_deleted  mt_is_system  
0                 1             0  
1                 0             0  
2                 1             0  
3                 1             0  
4                 1             0  
...             ...           ...  
4470              0             0  
4471              0             0  
4472              0             0  
4473              0             0  
4474              0             0  

[4475 rows x 14 columns]

In [13]:
mt_posts = posts.loc[posts['msg_topic_id'] == 2]
mt_posts

msg_id  msg_topic_id    msg_date  \
1       2             2  1316174048   
2       3             2  1316183999   
3       4             2  1316186941   
4       5             2  1316187178   
5       6             2  1316187891   

                                            msg_post  \
1  \n<p>Who are we hosting this forum from?</p>\n...   
2  <p>Crisis Host - they basically provide hostin...   
3  <p>Thank you, I'll make a note of it, I am ver...   
4  <p>If you mean the dark+orange skin then that'...   
5  <p>The functionality mostly, thanks for the in...   

                       msg_post_key  msg_author_id   msg_ip_address  \
1  9204e4883321af2275a37138d054a3f1             11    109.78.212.13   
2  12fd0309239711d02b39127de3502c51              1  178.140.119.217   
3  0658c6f99ac18d90609ea074ae5eefe6             11    109.78.212.13   
4  570257864e3cb812eebc2de5e5919080              1  178.140.119.217   
5  aabeacc8f4ccc579c405d4248ef2d9d6             11    109.78.212.13   

   msg_is_first_post  
1                  1  
2                  0  
3                  0  
4                  0  
5                  0

In [14]:
mt_posts['msg_post']

1    \n<p>Who are we hosting this forum from?</p>\n...
2    <p>Crisis Host - they basically provide hostin...
3    <p>Thank you, I'll make a note of it, I am ver...
4    <p>If you mean the dark+orange skin then that'...
5    <p>The functionality mostly, thanks for the in...
Name: msg_post, dtype: object

In [17]:
mt_posts['msg_post'][5]

'<p>The functionality mostly, thanks for the info.</p>'

In [20]:
len(posts['msg_author_id'].unique())

877

In [21]:
authors = posts['msg_author_id'].unique()

In [23]:
mt_ids = topics["mt_id"].unique()

In [24]:
len(mt_ids)

4475

In [93]:
members = pd.read_csv("./data/iron_march_201911/csv/core_members.csv")

In [95]:
members["member_id"]

0           1
1           2
2           3
3           4
4           5
        ...  
1202    15214
1203    15215
1204    15216
1205    15217
1206    15218
Name: member_id, Length: 1207, dtype: int64

In [97]:
len(members["member_id"].unique())

1207

In [98]:
members["member_id"].max()

15218

In [27]:
links = {}

In [29]:
for mt_id in mt_ids:
    mt_posts = posts.loc[posts['msg_topic_id'] == mt_id]
    mt_post_authors = mt_posts["msg_author_id"].unique()
    for author in mt_post_authors:
        if author not in links:
            links[author] = {}
        for other_author in mt_post_authors:
            if other_author not in links[author]:
                links[author][other_author] = 0
            links[author][other_author] = links[author][other_author] + 1


In [55]:
number_co_posters = []
number_co_posts = []
for author in links:
    number_co_posters.append(len(links[author]))
    number_co_posts = number_co_posts + (list(links[author].values()))

In [56]:
np.array(number_co_posters).mean()

6.696693272519955

In [57]:
np.array(number_co_posts).mean()

2.4799931891707816

In [69]:
threshold = 2
edge_index = []
for author in links.keys():
    for co_author in links[author].keys():
        if author != co_author and links[author][co_author] > threshold:
            edge_index.append([author, co_author])

In [64]:
len(edge_index)/2

176.0

In [65]:
import torch
from torch_geometric.data import Data

In [70]:
edge_index = torch.tensor(edge_index, dtype=torch.long)

In [71]:
edge_index

tensor([[    1,    65],
        [    1,     0],
        [    1,   283],
        [    1,   287],
        [    1,  3721],
        [    1,  6260],
        [    1,  8346],
        [    1,  7424],
        [    1,  2220],
        [    1,  9288],
        [    1,  9549],
        [    1, 10083],
        [    1,  9930],
        [    1, 13831],
        [   16,    72],
        [   16,     0],
        [   14,    35],
        [   14,     8],
        [   14,    49],
        [   14,   108],
        [    2,    35],
        [    2,     0],
        [    2,   161],
        [    8,    14],
        [    8,   130],
        [   35,    14],
        [   35,     2],
        [   35,     4],
        [   35,    54],
        [   35,    23],
        [   35,     0],
        [   35,    37],
        [    3,     0],
        [    9,     0],
        [   37,   130],
        [   37,    35],
        [   37,   164],
        [    4,    35],
        [    4,     0],
        [    4,   279],
        [    0,     2],
        [    0, 

In [72]:
edge_index=edge_index.t().contiguous() # this is what pytorch geometric wants

In [75]:
edge_index[0][0]

tensor(1)

In [76]:
edge_index[1][0]

tensor(65)

In [77]:
x = torch.zeros(len(posts['msg_author_id'].unique()))

In [78]:
x

tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 

In [79]:
data = Data(x=x, edge_index=edge_index)

In [80]:
data

Data(edge_index=[2, 352], x=[877])

In [114]:
from data import get_ironmarch_network_data

In [115]:
data = get_ironmarch_network_data()

In [116]:
data

Data(edge_index=[2, 352], x=[877])

In [117]:
data.edge_index

tensor([[    1,     1,     1,     1,     1,     1,     1,     1,     1,     1,
             1,     1,     1,     1,    16,    16,    14,    14,    14,    14,
             2,     2,     2,     8,     8,    35,    35,    35,    35,    35,
            35,    35,     3,     9,    37,    37,    37,     4,     4,     4,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,    40,     7,     7,     7,     7,     7,
             7,     7,    54,    54,    44,    23,    13,    49,    49,    49,
            49,    67,    84,    84,    91,    91,  

In [87]:
from torch_geometric.utils import train_test_split_edges

In [88]:
train_test_split_edges(data)

IndexError: index 8346 is out of bounds for dimension 0 with size 877

In [89]:
data

Data(test_pos_edge_index=[2, 17], train_pos_edge_index=[2, 302], val_pos_edge_index=[2, 8], x=[877])

In [106]:
ids = list(links.keys())

In [108]:
ids.sort()

In [113]:
ids.index(100)

50

In [112]:
ids

[0,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 16,
 17,
 19,
 20,
 22,
 23,
 28,
 29,
 35,
 37,
 39,
 40,
 43,
 44,
 47,
 48,
 49,
 50,
 53,
 54,
 56,
 61,
 62,
 63,
 64,
 65,
 67,
 68,
 72,
 79,
 84,
 85,
 86,
 89,
 91,
 100,
 101,
 104,
 108,
 112,
 114,
 125,
 129,
 130,
 131,
 132,
 133,
 134,
 138,
 139,
 140,
 142,
 144,
 146,
 150,
 151,
 152,
 157,
 158,
 159,
 160,
 161,
 164,
 168,
 173,
 174,
 175,
 182,
 188,
 191,
 197,
 204,
 205,
 206,
 207,
 208,
 234,
 236,
 239,
 240,
 246,
 255,
 261,
 263,
 266,
 267,
 269,
 271,
 274,
 279,
 281,
 283,
 287,
 288,
 293,
 296,
 298,
 299,
 302,
 304,
 315,
 317,
 319,
 323,
 329,
 333,
 335,
 336,
 338,
 342,
 348,
 353,
 358,
 361,
 364,
 368,
 372,
 422,
 446,
 495,
 505,
 563,
 660,
 663,
 805,
 821,
 857,
 861,
 862,
 887,
 945,
 958,
 960,
 991,
 1014,
 1066,
 1074,
 1080,
 1104,
 1109,
 1176,
 1209,
 1368,
 1558,
 1608,
 1730,
 1744,
 1772,
 1793,
 1986,
 2027,
 2037,
 2075,
 2082,
 2099,
 2113,
 2144,
 2170